package moses.client.service.helpers;

public enum EMessageTypes {
	SPAMMABLE, REQUESTC2DM, REQUESTINSTALLEDAPK, REQUESTGETAPKINFO, ACTIVITYPRINTMESSAGE, REQUESTGETLISTAPK, REQUESTDOWNLOADLINK, REQUESTGETFILTER, REQUESTGETHARDWAREPARAMETERS, REQUESTSETFILTER, REQUESTSETHARDWAREPARAMETERS
}
