package de.da_sense.moses.client.service.helpers;

/**
 * 
 * enum of all HookTypes
 * @Types POSTLOGOUT, POSTLOGINSUCCESS, POSTLOGINSUCCESSPRIORITY, POSTLOGINFAILED, POSTLOGINSTART, POSTLOGINEND
 */
public enum EHookTypes {
	POSTLOGOUT, POSTLOGINSUCCESS, POSTLOGINSUCCESSPRIORITY, POSTLOGINFAILED, POSTLOGINSTART, POSTLOGINEND
}
