package de.da_sense.moses.client.service.helpers;

/**
 * enum of all Message Types
 * @Types SPAMMABLE, REQUESTC2DM, REQUESTINSTALLEDAPK, REQUESTUNINSTALLEDAPK, REQUESTGETAPKINFO, ACTIVITYPRINTMESSAGE, REQUESTGETLISTAPK, REQUESTDOWNLOADLINK, REQUESTGETFILTER, REQUESTGETHARDWAREPARAMETERS, REQUESTSETFILTER, REQUESTSETHARDWAREPARAMETERS, REQUESTUPDATEHARDWAREPARAMETERS
 *
 */
public enum EMessageTypes {
	SPAMMABLE, REQUESTC2DM, REQUESTINSTALLEDAPK, REQUESTUNINSTALLEDAPK, REQUESTGETAPKINFO,
	ACTIVITYPRINTMESSAGE, REQUESTGETLISTAPK, REQUESTDOWNLOADLINK, REQUESTGETFILTER, REQUESTGETHARDWAREPARAMETERS,
	REQUESTSETFILTER, REQUESTSETHARDWAREPARAMETERS, REQUESTUPDATEHARDWAREPARAMETERS, REQUESTSETQUESTIONNAIREANSWERS
}
