package de.da_sense.moses.client.service.helpers;

/**
 * Enum of all Message Types
 * @author Wladimir Schmidt
 *
 */
public enum MessageTypesEnum {
	SPAMMABLE, 
	REQUEST_C2DM, 
	REQUEST_INSTALLED_APK, 
	REQUEST_UNINSTALLED_APK, 
	REQUEST_GET_APK_INFO,
	ACTIVITY_PRINT_MESSAGE, 
	REQUEST_GET_LIST_APK, 
	REQUEST_DOWNLOAD_LINK, 
	REQUEST_GET_FILTER, 
	REQUEST_GET_HARDWARE_PARAMETERS,
	REQUEST_SET_FILTER, 
	REQUEST_SET_HARDWARE_PARAMETERS, 
	REQUEST_UPDATE_HARDWARE_PARAMETERS, 
	REQUEST_SET_QUESTIONNAIRE_ANSWERS
}
