package de.da_sense.moses.client.service.helpers;

public enum EMessageTypes {
	SPAMMABLE, REQUESTC2DM, REQUESTINSTALLEDAPK, REQUESTUNINSTALLEDAPK, REQUESTGETAPKINFO, ACTIVITYPRINTMESSAGE, REQUESTGETLISTAPK, REQUESTDOWNLOADLINK, REQUESTGETFILTER, REQUESTGETHARDWAREPARAMETERS, REQUESTSETFILTER, REQUESTSETHARDWAREPARAMETERS, REQUESTUPDATEHARDWAREPARAMETERS
}
